### ISSUE TITLE
List of other developers interested in D3 + X3DOM

### ISSUE THREAD

**Issue by jamesleesaunders** [jamesleesaunders/d3-x3dom#40]
This issue is a simple list of other developers / resources which are in the D3 + 3D space. 
This is also a cheeky reach out to any of these developers, to see if any of you are still interested in this area, and a call to see if anyone may be interested in contributing to [d3-x3dom](https://github.com/jamesleesaunders/d3-x3dom) a 3D charts library built with D3 and X3DOM ? 
It would be amazing if we could all join forces in this relatively untouched area of d3 data viz. It not interested, no worries.

**D3 + X3DOM**
@wangchaowei https://github.com/wangchaowei/D3-X3DOM
@bwlewis https://github.com/bwlewis/x3dom
@Maputo https://github.com/Maputo/3DGraphVis
@mattbullen https://github.com/mattbullen/3D-scatterplot
@coderextreme https://github.com/coderextreme/d3orbitx3d
@hlvoorhees http://bl.ocks.org/hlvoorhees/5986172
@ZJONSSON http://bl.ocks.org/ZJONSSON/1291667
@sressler https://gist.github.com/sressler/3152017

**D3 + Three**
@Niekes https://github.com/Niekes/d3-3d
@vicapow https://github.com/vicapow/dz

** Already Contacted #8 Huge Thanks! **
@fabid https://github.com/fabid/d3-x3dom-shape
@camio http://bl.ocks.org/camio/5087116

**Comment by coderextreme** [comment]
I’d be interested in doing something with kibana: https://www.youtube.com/watch?v=AZbO2Y8NNS8 (Very old). Not sure about working on a lower level tool like d3.js or x3dom.  Also, look at Power BI, glTF and X_ITE. Working on really low level stuff is going to take a very long time to see results, but if you have a good idea, let’s hear it.  I think working on SAI for X3D with D3.js may have a lot of good results for Data-Driven 3D!

I am not really sure of the future of X3DOM since the primary developers aren’t contributing as much (yearly releases I think), but there are developers, so that’s good (we can get our changes merged).

So I think we should focus on Data-Driven 3D instead of D3 + X3DOM.

My own tool is trying to treat X_ITE and X3DOM as a porting interface, adding a PROTO expander to X3DOM, and JSON encoding for X3D to both.

Might I suggest a project of bringing VRMLScript to X3DOM?   This is bringing routes to scripting in X3DOM.

Also, there’s a big push to getting X3Dv4 out which means getting a standardized X3D/VRML environment for HTML5.   Join the x3d-public mailing list.   Join the web3d consortium.  That’s probable the best place to put your effort at this time, but it’s definitely not dataviz.  Here’s the overview:  http://www.web3d.org/x3d4

If anyone has a use for a prismatic effect on a visualization, I can help.

In the visualization world, I tend to do more visualization of documents and schemas, if someone wants to work on new ways of 3D visualizing documents and schemas, I’m all ears.

John

Sent from Mail for Windows 10

From: James Saunders
Sent: Sunday, November 25, 2018 10:28 AM
To: jamesleesaunders/d3-x3dom
Cc: John Carlson; Mention
Subject: [jamesleesaunders/d3-x3dom] List of other developers interested in D3+ X3DOM (#40)

This issue is a simple list of other developers / resources which are in the D3 + 3D space.
This is also a cheeky reach out to any of these developers, to see if any of you are still interested in this area, and a call to see if anyone may be interested in contributing to d3-x3dom ? It would be amazing if we could all join forces in this relatively untouched area of d3 data viz. It not interested, no worries.
D3 + X3DOM
@wangchaowei https://github.com/wangchaowei/D3-X3DOM
@bwlewis https://github.com/bwlewis/x3dom
@Maputo https://github.com/Maputo/3DGraphVis
@mattbullen https://github.com/mattbullen/3D-scatterplot
@coderextreme https://github.com/coderextreme/d3orbitx3d
@hlvoorhees http://bl.ocks.org/hlvoorhees/5986172
@ZJONSSON http://bl.ocks.org/ZJONSSON/1291667
@sressler https://gist.github.com/sressler/3152017
D3 + Three
@Niekes https://github.com/Niekes/d3-3d
@vicapow https://github.com/vicapow/dz
** Already Contacted #8 Huge Thanks! **
@fabid https://github.com/fabid/d3-x3dom-shape
@camio http://bl.ocks.org/camio/5087116

**Comment by coderextreme** [comment]
Yeah, I think you should work with ELK (Elastic Search, Log Stash, Kibana).   You're like components, and they are the whole package. You'll get a lot more visibility for your components in Kibana.  You do have to sign some agreement, but it's not too bad.

**Comment by coderextreme** [comment]
Looks like Beats may be an application of interest too.  It's from the same company as ELK.

**Comment by coderextreme** [comment]
Such reusable charts could be used inside Kibana.

John

Sent from Mail for Windows 10
